import re, pathlib, hashlib, base64, json
from glob import glob

local = dict()
pathlib.Path('../' + (filename := 'imgdata')).mkdir(exist_ok=True, parents=True)
# (pathlib.Path('../{filename}') / path.parent.parent.name / path.parent.name).mkdir(exist_ok=True, parents=True)
with open('../imgdata/.htaccess', 'wt', encoding='utf8') as file:
    file.write('# autogenerated, do not edit\n')
    file.write('RewriteEngine on\n')
    file.write('RewriteBase /gallery/imgdata/\n')
    file.write('RewriteCond %{HTTP:Sec-Fetch-Site} ^cross-site$ [NC]\n')
    file.write('RewriteRule ^ - [F,L]\n')
    file.write('Header append vary sec-fetch-site\n')
    file.write('Header set Cache-Control "public, max-age=31536000, immutable"\n\n')
    file.write('ErrorDocument 404 /gallery/imgdata/404placeholder.webp\n')
    file.write('ErrorDocument 403 /gallery/imgdata/404placeholder.webp\n')
pass
for i in glob('universe-images/*/*/'):
    for path in pathlib.Path(i).iterdir():
        if path.is_file():
            if path.suffix == '.php':
                continue
            if path.suffix == '.kra':
                continue
            if path.suffix == '.json':
                continue
            if path.name == 'altText.txt':
                continue
            if not (path.name.startswith('main') or path.name.startswith('ai.main')):
                continue
            with open(path, 'rb') as file, open(pathlib.Path(i) / 'main.json', 'rb') as jsonfile:
                cont = file.read()
                hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                    .replace('/', '_').replace('+', '-').replace('=', str())
                data = jsonfile.read()
            with open(f'../{filename}/{hash}{path.suffix}', 'wb') as file:
                file.write(cont)
            local[path.parent.parent.name] = local.get(path.parent.parent.name, dict())
            local[path.parent.parent.name][path.parent.name] = local[path.parent.parent.name].get(path.parent.name, {
                'universe': path.parent.parent.name, 'charId': path.parent.name, 'assets': list(),
                'main.json': json.loads(data)
            })
            asset = dict(hash=f'{hash}{path.suffix}', oname=path.name, origin='main')
            # local[path.parent.parent.name][path.parent.name]['assets'].append(asset)
            local[path.parent.parent.name][path.parent.name]['main-see'] = None
            local[path.parent.parent.name][path.parent.name]['main-ai'] = None
            asset['isAi'] = path.name.startswith('ai.')
            asset['oName'] = path.name
            if path.name.startswith('ai.'):
                local[path.parent.parent.name][path.parent.name]['main-ai'] = asset
            else:
                local[path.parent.parent.name][path.parent.name]['main-see'] = asset
    for path in pathlib.Path(i).iterdir():
        if path.is_dir():
            if path.name == 'gallery':
                for inner_path in path.iterdir():
                    if inner_path.name == 'ai':
                        for inner_inner_path in inner_path.iterdir():
                            if inner_inner_path.suffix == '.kra':
                                continue
                            with open(inner_inner_path, 'rb') as file:
                                cont = file.read()
                                hash = base64.b64encode(hashlib.sha512().digest()).decode('utf-8') \
                                    .replace('/', '_').replace('+', '-').replace('=', str())
                            with open(f'../{filename}/{hash}{inner_inner_path.suffix}', 'wb') as file:
                                file.write(cont)
                            datapath = inner_inner_path.parent.parent;
                            asset = dict(hash=f'{hash}{inner_inner_path.suffix}', oname=inner_inner_path.name)
                            local[datapath.parent.parent.name][datapath.parent.name]['assets'].append(asset)
                            asset['origin'] = 'ai'
                            asset['isAi'] = True
                        continue
                    if inner_path.suffix == '.kra':
                        continue
                    with open(inner_path, 'rb') as file:
                        cont = file.read()
                        hash = base64.b64encode(hashlib.sha512().digest()).decode('utf-8') \
                            .replace('/', '_').replace('+', '-').replace('=', str())
                    with open(f'../{filename}/{hash}{inner_path.suffix}', 'wb') as file:
                        file.write(cont)
                    datapath = inner_path.parent;
                    asset = dict(hash=f'{hash}{inner_path.suffix}', oname=inner_path.name)
                    local[datapath.parent.parent.name][datapath.parent.name]['assets'].append(asset)
                    asset['origin'] = 'gallery'
                    asset['isAi'] = False
    pass


def copyfile(src: str, out: str):
    with open(src, 'rb') as src_file, open(out, 'wb') as out_file:
        out_file.write(src_file.read())


copyfile('404placeholder.webp', '../imgdata/404placeholder.webp')

with open(f'../{filename}/.assets.json', 'wt', encoding='utf8') as file:
    file.write(json.dumps(local).replace('oname', 'oName'))
pass
