import re, pathlib, hashlib, base64, json, requests, shutil
from glob import glob


def copyfile(src: str, out: str):
    with open(src, 'rb') as src_file, open(out, 'wb') as out_file:
        out_file.write(src_file.read())


def main():
    print('make-ready')
    local = dict()
    shutil.rmtree('../' + (filename := 'imgdata'))
    pathlib.Path('../' + (filename := 'imgdata')).mkdir(exist_ok=True, parents=True)
    # (pathlib.Path('../{filename}') / path.parent.parent.name / path.parent.name).mkdir(exist_ok=True, parents=True)
    with open('../imgdata/.htaccess', 'wt', encoding='utf8') as file:
        file.write('# autogenerated, do not edit\n')
        file.write('RewriteEngine on\n')
        file.write('RewriteBase /gallery/imgdata/\n')
        file.write('RewriteCond %{HTTP:Sec-Fetch-Site} ^cross-site$ [NC]\n')
        file.write('RewriteRule ^ - [F,L]\n')
        file.write('Header append vary sec-fetch-site\n')
        file.write('Header set Cache-Control "public, max-age=31536000, immutable"\n\n')
        file.write('ErrorDocument 404 /gallery/imgdata/404placeholder.webp\n')
        file.write('ErrorDocument 403 /gallery/imgdata/404placeholder.webp\n')
    pass
    for i in glob('universe-images/*/*/'):
        for path in pathlib.Path(i).iterdir():
            if path.is_file():
                if path.suffix not in ['.png', '.jpeg', '.jpg', '.webp', '.avif']:
                    continue
                if not (path.name.startswith('main') or path.name.startswith('ai.main')):
                    continue
                with open(path, 'rb') as file, open(pathlib.Path(i) / 'main.json', 'rb') as jsonfile:
                    cont = file.read()
                    hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                        .replace('/', '_').replace('+', '-').replace('=', str())
                    data = jsonfile.read()
                with open(f'../{filename}/{hash}{path.suffix}', 'wb') as file:
                    file.write(cont)
                local[path.parent.parent.name] = local.get(path.parent.parent.name, dict())
                local[path.parent.parent.name][path.parent.name] = local[path.parent.parent.name].get(
                    path.parent.name, {
                        'charId': path.parent.name,  # 'universe': path.parent.parent.name,
                        'assets': list(), 'main.json': json.loads(data)
                    })
                hashed = f'{hash}{path.suffix}'
                resp = requests.get(url := f'http://localhost/gallery/dev-only/imgdata.php?hash={hashed}')
                matched = re.search('w=(\\d+), h=(\\d+)', resp.headers['image-size'])
                asset = dict(hash=hashed, oname=path.name, origin='main',
                             w=int(matched.group(1)), h=int(matched.group(2)),
                             t=resp.headers['image-type'])
                # local[path.parent.parent.name][path.parent.name]['assets'].append(asset)
                local[path.parent.parent.name][path.parent.name]['main-see'] = \
                    local[path.parent.parent.name][path.parent.name].get('main-see', dict())
                local[path.parent.parent.name][path.parent.name]['main-ai'] = \
                    local[path.parent.parent.name][path.parent.name].get('main-ai', dict())
                # asset['isAi'] = path.name.startswith('ai.')
                if path.name.startswith('ai.'):
                    local[path.parent.parent.name][path.parent.name]['main-ai'][path.suffix[1:]] = asset
                else:
                    local[path.parent.parent.name][path.parent.name]['main-see'][path.suffix[1:]] = asset
        for path in pathlib.Path(i).iterdir():
            if path.is_dir():
                if path.name == 'gallery':
                    for inner_path in path.iterdir():
                        if inner_path.name == 'ai':
                            for inner_inner_path in inner_path.iterdir():
                                if inner_inner_path.suffix == '.kra':
                                    continue
                                with open(inner_inner_path, 'rb') as file:
                                    cont = file.read()
                                    hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                                        .replace('/', '_').replace('+', '-').replace('=', str())
                                with open(f'../{filename}/{hash}{inner_inner_path.suffix}', 'wb') as file:
                                    file.write(cont)
                                datapath = inner_inner_path.parent.parent;
                                asset = dict(hash=f'{hash}{inner_inner_path.suffix}', oname=inner_inner_path.name)
                                local[datapath.parent.parent.name][datapath.parent.name]['assets'].append(asset)
                                asset['origin'] = 'ai'
                                asset['isAi'] = True
                            continue
                        if inner_path.suffix == '.kra':
                            continue
                        with open(inner_path, 'rb') as file:
                            cont = file.read()
                            hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                                .replace('/', '_').replace('+', '-').replace('=', str())
                        with open(f'../{filename}/{hash}{inner_path.suffix}', 'wb') as file:
                            file.write(cont)
                        datapath = inner_path.parent;
                        asset = dict(hash=f'{hash}{inner_path.suffix}', oname=inner_path.name)
                        local[datapath.parent.parent.name][datapath.parent.name]['assets'].append(asset)
                        asset['origin'] = 'gallery'
                        asset['isAi'] = False
        pass

    for outer in local.values():
        for inner in outer.values():
            data_dict = dict()
            data_ai_dict = dict()
            for asset in inner['assets']:
                *names, suffix = asset['oname'].split('.')
                name = '.'.join(names)
                local_dict = data_ai_dict if asset['isAi'] else data_dict
                local_dict[name] = local_dict.get(name, dict())
                resp = requests.get(url := f'http://localhost/gallery/dev-only/imgdata.php?hash={asset['hash']}')
                # print(resp.status_code, url)
                # for key, val in dict(resp.headers).items():
                #     print(f'{key}: {val}')
                # print()
                matched = re.search('w=(\\d+), h=(\\d+)', resp.headers['image-size'])
                local_dict[name][suffix] = {
                    'hash': asset['hash'], 'origin': asset['origin'],
                    'w': int(matched.group(1)), 'h': int(matched.group(2)),
                    't': resp.headers['image-type'], 'oName': asset['oname']}
            inner['asset2'] = data_dict
            inner['assetAi'] = data_ai_dict
            del inner['assets']

    unidata = dict()
    for i in glob('universe-images/*/universe-img.webp'):
        with open(i, 'rb') as file:
            cont = file.read()
            hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                .replace('/', '_').replace('+', '-').replace('=', str())
        with open(f'../{filename}/{hash}{pathlib.Path(i).suffix}', 'wb') as file:
            file.write(cont)
        resp = requests.get(url := f'http://localhost/gallery/dev-only/imgdata.php?hash={hash}{pathlib.Path(i).suffix}')
        matched = re.search('w=(\\d+), h=(\\d+)', resp.headers['image-size'])
        unidata[pathlib.Path(i).parent.stem] = {
            'hash': f'{hash}{pathlib.Path(i).suffix}',
            'w': int(matched.group(1)), 'h': int(matched.group(2)),
            'origin': 'universe', 't': resp.headers['image-type']}
    copyfile('404placeholder.webp', '../imgdata/404placeholder.webp')
    with open(f'../{filename}/.assets.json', 'wt', encoding='utf8') as file:
        file.write(json.dumps(dict(chardata=local, unidata=unidata), indent=2))
    pass


if __name__ == '__main__':
    main()
