import re, pathlib, hashlib, base64, json, requests, shutil
from datetime import datetime, timezone
from htmlparser import html_to_jsonml
from glob import glob


def copyfile(src: str, out: str):
    with open(src, 'rb') as src_file, open(out, 'wb') as out_file:
        out_file.write(src_file.read())


def main():
    local = dict()
    htmls = list()
    errors = False
    print('make-ready')
    shutil.rmtree('../' + (folder := 'imgdata'))
    pathlib.Path('../' + folder).mkdir(exist_ok=True, parents=True)
    # (pathlib.Path('../{folder}') / path.parent.parent.name / path.parent.name).mkdir(exist_ok=True, parents=True)
    with open('../imgdata/.htaccess', 'wt', encoding='utf8') as file:
        file.write('# autogenerated, do not edit\n')
        file.write('RewriteEngine on\n')
        file.write('RewriteBase /gallery/imgdata/\n')
        file.write('RewriteCond %{HTTP:Sec-Fetch-Site} ^cross-site$ [NC]\n')
        file.write('RewriteRule ^ - [F,L]\n')
        file.write('Header append vary sec-fetch-site\n')
        # file.write('Header set Cache-Control "public, max-age=10"\n\n')
        file.write('Header set Cache-Control "public, max-age=31536000, immutable"\n\n')
        file.write('ErrorDocument 404 /gallery/imgdata/404placeholder.webp\n')
        file.write('ErrorDocument 403 /gallery/imgdata/404placeholder.webp\n')
    for i in glob('universe-images/*/*/'):
        with open(pathlib.Path(i) / 'main.json', 'rb') as jsonfile:
            try:
                main_json = json.loads(jsonfile.read())
            except json.decoder.JSONDecodeError:
                print('error while proccessing:', (pathlib.Path(i) / 'main.json').resolve())
                errors = True
                continue
        for path in pathlib.Path(i).iterdir():
            if path.is_file():
                if path.suffix in {'.html'}:
                    htmls.append(path)
                    continue
                if path.suffix not in {'.png', '.jpeg', '.jpg', '.webp', '.avif'}:
                    continue
                if not (path.name.startswith('main') or path.name.startswith('ai.main')):
                    continue
                with open(path, 'rb') as file:
                    cont = file.read()
                    hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                        .replace('/', '_').replace('+', '-').replace('=', str())
                with open(f'../{folder}/{hash}{path.suffix}', 'wb') as file:
                    file.write(cont)
                local[path.parent.parent.name] = local.get(path.parent.parent.name, dict())
                local[path.parent.parent.name][path.parent.name] = local \
                    [path.parent.parent.name].get(path.parent.name, {
                    'charId': path.parent.name, 'assets': list(),
                    'main.json': main_json, 'htdesc': None})
                hashed = f'{hash}{path.suffix}'
                resp = requests.get(f'http://localhost/gallery/dev-only/imgdata.php?hash={hashed}')
                sizes = resp.headers.get('image-size')
                if sizes is None:
                    print(pathlib.Path(i), 'failed because it isnt found')
                    continue
                matched = re.search('w=(\\d+), h=(\\d+)', sizes)
                asset = dict(hash=hashed, oname=path.name,
                             w=int(matched.group(1)), h=int(matched.group(2)),
                             t=resp.headers['image-type'], origin='main')
                local[path.parent.parent.name][path.parent.name]['main-see'] = \
                    local[path.parent.parent.name][path.parent.name].get('main-see', dict())
                local[path.parent.parent.name][path.parent.name]['main-ai'] = \
                    local[path.parent.parent.name][path.parent.name].get('main-ai', dict())
                if path.name.startswith('ai.'):
                    local[path.parent.parent.name][path.parent.name]['main-ai'][path.suffix[1:]] = asset
                else:
                    local[path.parent.parent.name][path.parent.name]['main-see'][path.suffix[1:]] = asset
        for path in pathlib.Path(i).iterdir():
            if path.is_dir():
                if path.name == 'gallery':
                    for inner_path in path.iterdir():
                        if inner_path.name == 'ai':
                            for inner_inner_path in inner_path.iterdir():
                                if inner_inner_path.suffix not in {'.png', '.jpeg', '.jpg', '.webp', '.avif'}:
                                    continue
                                with open(inner_inner_path, 'rb') as file:
                                    cont = file.read()
                                    hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                                        .replace('/', '_').replace('+', '-').replace('=', str())
                                with open(f'../{folder}/{hash}{inner_inner_path.suffix}', 'wb') as file:
                                    file.write(cont)
                                datapath = inner_inner_path.parent.parent
                                asset = dict(hash=f'{hash}{inner_inner_path.suffix}', oname=inner_inner_path.name)
                                local[datapath.parent.parent.name][datapath.parent.name]['assets'].append(asset)
                                asset['origin'] = 'ai'
                                asset['isAi'] = True
                            continue
                        if inner_path.suffix not in {'.png', '.jpeg', '.jpg', '.webp', '.avif'}:
                            continue
                        with open(inner_path, 'rb') as file:
                            cont = file.read()
                            hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                                .replace('/', '_').replace('+', '-').replace('=', str())
                        with open(f'../{folder}/{hash}{inner_path.suffix}', 'wb') as file:
                            file.write(cont)
                        datapath = inner_path.parent
                        asset = dict(hash=f'{hash}{inner_path.suffix}', oname=inner_path.name)
                        local[datapath.parent.parent.name][datapath.parent.name]['assets'].append(asset)
                        asset['origin'] = 'gallery'
                        asset['isAi'] = False
    for outer in local.values():
        for inner in outer.values():
            data_dict = dict()
            data_ai_dict = dict()
            for asset in inner['assets']:
                *names, suffix = asset['oname'].split('.')
                name = '.'.join(names)
                local_dict = data_ai_dict if asset['isAi'] else data_dict
                local_dict[name] = local_dict.get(name, dict())
                resp = requests.get(f'http://localhost/gallery/dev-only/imgdata.php?hash={asset['hash']}')
                sizes = resp.headers.get('image-size')
                if sizes is None:
                    continue
                matched = re.search('w=(\\d+), h=(\\d+)', sizes)
                local_dict[name][suffix] = {
                    'hash': asset['hash'], 'origin': asset['origin'],
                    'w': int(matched.group(1)), 'h': int(matched.group(2)),
                    't': resp.headers['image-type'], 'oname': asset['oname']}
            inner['asset2'] = data_dict
            inner['assetAi'] = data_ai_dict
            del inner['assets']
        with open(f'./universe-images/universes.json', 'rt', encoding='utf8') as file:
            univ = json.load(file)
    unidata = dict()
    for i in [
        *glob('universe-images/*/universe-img.*'),
        *glob('universe-images/*/universe-img-ai.*'),
    ]:
        if pathlib.Path(i).suffix not in {'.png', '.webp'}:
            continue
        with open(i, 'rb') as file:
            cont = file.read()
            hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                .replace('/', '_').replace('+', '-').replace('=', str())
        with open(f'../{folder}/{hash}{pathlib.Path(i).suffix}', 'wb') as file:
            file.write(cont)
        resp = requests.get(f'http://localhost/gallery/dev-only/imgdata.php?hash={hash}{pathlib.Path(i).suffix}')
        # print(resp.status_code, url)
        # for key, val in dict(resp.headers).items():
        #     print(f'{key}: {val}')
        # print()
        sizes = resp.headers.get('image-size')
        if sizes is None:
            print(pathlib.Path(i), 'failed because it isnt found')
            continue
        matched = re.search('w=(\\d+), h=(\\d+)', sizes)
        uniname = pathlib.Path(i).parent.stem
        unidata[uniname] = unidata.get(uniname, {
            'humanName': univ.get(uniname, uniname),
            "noAi": dict(), "wiAi": dict()})
        unidata[uniname]['wiAi' if pathlib.Path(i).stem.endswith('-ai') else 'noAi'][pathlib.Path(i).suffix[1:]] = {
            'hash': f'{hash}{pathlib.Path(i).suffix}', 'w': int(matched.group(1)), 'h': int(matched.group(2)),
            'origin': 'universe', 't': resp.headers['image-type']}
    nokeys = set(unidata.keys())
    for thing in sorted(set(univ.keys()) - nokeys):
        unidata[thing] = {'humanName': univ[thing]}

    new = dict(main=local['main'])
    for key, val in local.items():
        if key == 'main': continue
        sorted_items = [(inner_key, inner_val) for inner_key, inner_val in val.items()]
        sorted_items.sort(key=lambda dat: (
            1 if dat[1]["main.json"]['UniverseId'] == 'RecycleReady' else 0,
            0  # datetime.fromisoformat(dat[1]["main.json"]['creationDate']).timestamp()
        ))
        new[key] = {char_id: char_data for char_id, char_data in sorted_items}
    local = new
    step0 = [(key, val) for key, val in local['main'].items()]
    step0.sort(key=lambda dat: datetime.fromisoformat(dat[1]["main.json"]['creationDate']).timestamp())

    def get_sort_key(item):
        u_id = str(item[1]["main.json"].get('UniverseId', ''))
        is_favicond = 0 if u_id == 'Favicond-Main' else 1
        return is_favicond, unidata.get(u_id, dict()).get('humanName', u_id)

    # Sort the items according to UniverseId custom hierarchy
    sorted_items = sorted(step0, key=get_sort_key)

    # Reconstruct local['main'] back into its original dict structure { char_id: char_data }
    local['main'] = {char_id: char_data for char_id, char_data in sorted_items}
    pass  # gemini end
    copyfile('404placeholder.webp', '../imgdata/404placeholder.webp')
    reverse_map = dict()
    for unid, char in local.items():
        for charid in char:
            if reverse_map.get(charid) is not None:
                print(charid, 'is a duplicate of another')
                errors = True
            reverse_map[charid] = unid

    for htmld in htmls:
        with open(htmld, 'rb') as file:
            content = file.read()
            hashed = base64.b64encode(hashlib.sha512(content).digest()).decode('utf-8') \
                .replace('/', '_').replace('+', '-').replace('=', str())

        with open(f'../{folder}/{hashed}.html.json', 'wt', encoding='utf8') as file:
            htdata = html_to_jsonml(
                '<body>' + content.replace(b'\r\n', b'\n')
                .replace(b'\r', b'\n').decode('utf-8') + '</body>')
            file.write(json.dumps(process_htdata(htdata, reverse_map)))
        local[pathlib.Path(htmld).parent.parent.name] \
            [pathlib.Path(htmld).parent.name] \
            ["htdesc"] = f"{hashed}.html.json"
        # print(pathlib.Path(htmld).resolve())
    with open(f'../{folder}/.assets.json', 'wt', encoding='utf8') as file:
        file.write(json.dumps(dict(
            chardata=local, unidata=unidata, rev_map=reverse_map,
        ), sort_keys=False))
    with open('../imgdata/.htaccess', 'at', encoding='utf8') as file:
        for univ, outer in local.items():
            for charid, inner in outer.items():
                if inner['main-see']:
                    for data in inner['main-see'].values():
                        write_file(file, data, inner['main.json'], charid, univ, unidata)
                    for data in inner['main-ai'].values():
                        write_file(file, data, inner['main.json'], charid, univ, unidata)
                    for thing in inner['asset2'].values():
                        for formats in thing.values():
                            write_file(file, formats, inner['main.json'], charid, univ, unidata)
                    for thing in inner['assetAi'].values():
                        for formats in thing.values():
                            write_file(file, formats, inner['main.json'], charid, univ, unidata)
                    pass
    return errors


pass  # def printreturn(*args, **kwargs):print(*args, kwargs)return args


def process_htdata(htdata, context):
    return transform_jsonml(htdata, {
        'char-rel': (lambda element: process_char_ref(element, context)),
    })


# tag = element[0]
# return ["a", attrs] + element[2:]
def process_char_ref(element, context):
    href = None
    if bool(uni_name := context.get(element[1].get('who'))):
        href = f'universe/{uni_name}/{element[1].get('who')}'
    attrs = dict(href=href)
    return ["a", attrs] + element[2:]


def transform_jsonml(node, handlers):
    """
    Recursively transforms a JsonML tree using a dictionary of handler functions.

    handlers: dict mapping tag names (str) to functions that take a full
              JsonML element list and return the replacement JsonML element list.
    """
    if not isinstance(node, list) or not node:
        return node

    tag_name = node[0]
    attrs = node[1]

    # First, recursively transform all child nodes (index 2 onwards)
    transformed_children = []
    for child in node[2:]:
        if isinstance(child, list):
            transformed_children.append(transform_jsonml(child, handlers))
        else:
            transformed_children.append(child)

    # Reconstruct the current element with transformed children
    current_element = [tag_name, attrs] + transformed_children

    # If a handler is defined for this element's tag name, apply it
    if tag_name in handlers:
        return handlers[tag_name](current_element)

    return current_element


def write_file(file, data, chardata, charid, univ, unidata):
    *names, suffix = data['hash'].split('.')
    name = '.'.join(names)
    file.write(f'\n<Files "{name}.{suffix}">\nHeader set\x20')
    file.write(f'content-disposition "inline; filename=\\"{chardata['name']}.{suffix}\\""')
    # file.write(f'\nHeader set fx-data-names "fx-data-name, fx-data-oname, fx-data-charname, fx-mkready,'
    #           ' fx-data-names, fx-relative-url, fx-data-mime, fx-data-w, fx-data-h, fx-data-univname"')
    if bool(human := unidata.get(univ, dict()).get('humanName')):
        file.write(f'\nHeader set fx-data-univname {encode_str_b64(human)}')
    file.write(f'\nHeader set fx-data-name {encode_str_b64(chardata['name'])}')
    file.write(f'\nHeader set fx-data-oname {encode_str_b64(data['oname'])}')
    file.write(f'\nHeader set fx-data-charname {encode_str_b64(charid)}')
    file.write(f'\nHeader set fx-relative-url /gallery/universe/{univ}/{charid}')
    file.write(f'\nHeader set fx-mkready "{date_now()}"')
    file.write(f'\nHeader set fx-data-mime {data['t']}')
    file.write(f'\nHeader set fx-data-w {data['w']}')
    file.write(f'\nHeader set fx-data-h {data['h']}')
    file.write(f'\n</Files>\n')


def date_now():
    now = datetime.now(timezone.utc)  # .astimezone()
    formatted_date = now.strftime("%a %b %d %Y %H:%M:%S GMT%z")
    return formatted_date  # formatted_date


def encode_str_b64(strx: str) -> str:
    return f':{base64.b64encode(strx.encode('utf8')).decode('utf8')}:'


if __name__ == '__main__':
    if main():
        input('enter to exit:')
pass
