import re, pathlib, hashlib, base64, json, requests, shutil
from datetime import datetime
from glob import glob


def copyfile(src: str, out: str):
    with open(src, 'rb') as src_file, open(out, 'wb') as out_file:
        out_file.write(src_file.read())


def main():
    print('make-ready')
    local = dict()
    shutil.rmtree('../' + (folder := 'imgdata'))
    pathlib.Path('../' + folder).mkdir(exist_ok=True, parents=True)
    # (pathlib.Path('../{folder}') / path.parent.parent.name / path.parent.name).mkdir(exist_ok=True, parents=True)
    with open('../imgdata/.htaccess', 'wt', encoding='utf8') as file:
        file.write('# autogenerated, do not edit\n')
        file.write('RewriteEngine on\n')
        file.write('RewriteBase /gallery/imgdata/\n')
        file.write('RewriteCond %{HTTP:Sec-Fetch-Site} ^cross-site$ [NC]\n')
        file.write('RewriteRule ^ - [F,L]\n')
        file.write('Header append vary sec-fetch-site\n')
        file.write('Header set Cache-Control "public, max-age=31536000, immutable"\n\n')
        file.write('ErrorDocument 404 /gallery/imgdata/404placeholder.webp\n')
        file.write('ErrorDocument 403 /gallery/imgdata/404placeholder.webp\n')
    pass
    for i in glob('universe-images/*/*/'):
        for path in pathlib.Path(i).iterdir():
            if path.is_file():
                if path.suffix not in {'.png', '.jpeg', '.jpg', '.webp', '.avif'}:
                    continue
                if not (path.name.startswith('main') or path.name.startswith('ai.main')):
                    continue
                with open(path, 'rb') as file, open(pathlib.Path(i) / 'main.json', 'rb') as jsonfile:
                    cont = file.read()
                    hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                        .replace('/', '_').replace('+', '-').replace('=', str())
                    data = jsonfile.read()
                with open(f'../{folder}/{hash}{path.suffix}', 'wb') as file:
                    file.write(cont)
                local[path.parent.parent.name] = local.get(path.parent.parent.name, dict())
                local[path.parent.parent.name][path.parent.name] = local[path.parent.parent.name].get(
                    path.parent.name, {
                        'charId': path.parent.name,  # 'universe': path.parent.parent.name,
                        'assets': list(), 'main.json': json.loads(data)
                    })
                hashed = f'{hash}{path.suffix}'
                resp = requests.get(f'http://localhost/gallery/dev-only/imgdata.php?hash={hashed}')
                sizes = resp.headers.get('image-size')
                if sizes is None:
                    print(pathlib.Path(i), 'failed because it isnt found')
                    continue
                matched = re.search('w=(\\d+), h=(\\d+)', sizes)
                asset = dict(hash=hashed, oname=path.name, origin='main',
                             w=int(matched.group(1)), h=int(matched.group(2)),
                             t=resp.headers['image-type'])
                local[path.parent.parent.name][path.parent.name]['main-see'] = \
                    local[path.parent.parent.name][path.parent.name].get('main-see', dict())
                local[path.parent.parent.name][path.parent.name]['main-ai'] = \
                    local[path.parent.parent.name][path.parent.name].get('main-ai', dict())
                if path.name.startswith('ai.'):
                    local[path.parent.parent.name][path.parent.name]['main-ai'][path.suffix[1:]] = asset
                else:
                    local[path.parent.parent.name][path.parent.name]['main-see'][path.suffix[1:]] = asset
        for path in pathlib.Path(i).iterdir():
            if path.is_dir():
                if path.name == 'gallery':
                    for inner_path in path.iterdir():
                        if inner_path.name == 'ai':
                            for inner_inner_path in inner_path.iterdir():
                                if inner_inner_path.suffix not in {'.png', '.jpeg', '.jpg', '.webp', '.avif'}:
                                    continue
                                with open(inner_inner_path, 'rb') as file:
                                    cont = file.read()
                                    hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                                        .replace('/', '_').replace('+', '-').replace('=', str())
                                with open(f'../{folder}/{hash}{inner_inner_path.suffix}', 'wb') as file:
                                    file.write(cont)
                                datapath = inner_inner_path.parent.parent
                                asset = dict(hash=f'{hash}{inner_inner_path.suffix}', oname=inner_inner_path.name)
                                local[datapath.parent.parent.name][datapath.parent.name]['assets'].append(asset)
                                asset['origin'] = 'ai'
                                asset['isAi'] = True
                            continue
                        if inner_path.suffix not in {'.png', '.jpeg', '.jpg', '.webp', '.avif'}:
                            continue
                        with open(inner_path, 'rb') as file:
                            cont = file.read()
                            hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                                .replace('/', '_').replace('+', '-').replace('=', str())
                        with open(f'../{folder}/{hash}{inner_path.suffix}', 'wb') as file:
                            file.write(cont)
                        datapath = inner_path.parent
                        asset = dict(hash=f'{hash}{inner_path.suffix}', oname=inner_path.name)
                        local[datapath.parent.parent.name][datapath.parent.name]['assets'].append(asset)
                        asset['origin'] = 'gallery'
                        asset['isAi'] = False
    for outer in local.values():
        for inner in outer.values():
            data_dict = dict()
            data_ai_dict = dict()
            for asset in inner['assets']:
                *names, suffix = asset['oname'].split('.')
                name = '.'.join(names)
                local_dict = data_ai_dict if asset['isAi'] else data_dict
                local_dict[name] = local_dict.get(name, dict())
                resp = requests.get(f'http://localhost/gallery/dev-only/imgdata.php?hash={asset['hash']}')
                sizes = resp.headers.get('image-size')
                if sizes is None:
                    print(pathlib.Path(i), 'failed because it isnt found')
                    continue
                matched = re.search('w=(\\d+), h=(\\d+)', sizes)
                local_dict[name][suffix] = {
                    'hash': asset['hash'], 'origin': asset['origin'],
                    'w': int(matched.group(1)), 'h': int(matched.group(2)),
                    't': resp.headers['image-type'], 'oname': asset['oname']}
            inner['asset2'] = data_dict
            inner['assetAi'] = data_ai_dict
            del inner['assets']
        with open(f'./universe-images/universes.json', 'rt', encoding='utf8') as file:
            univ = json.load(file)
    unidata = dict()
    for i in [
        *glob('universe-images/*/universe-img.*'),
        *glob('universe-images/*/universe-img-ai.*'),
    ]:
        if pathlib.Path(i).suffix not in {'.png', '.webp'}:
            continue
        with open(i, 'rb') as file:
            cont = file.read()
            hash = base64.b64encode(hashlib.sha512(cont).digest()).decode('utf-8') \
                .replace('/', '_').replace('+', '-').replace('=', str())
        with open(f'../{folder}/{hash}{pathlib.Path(i).suffix}', 'wb') as file:
            file.write(cont)
        resp = requests.get(f'http://localhost/gallery/dev-only/imgdata.php?hash={hash}{pathlib.Path(i).suffix}')
        # print(resp.status_code, url)
        # for key, val in dict(resp.headers).items():
        #     print(f'{key}: {val}')
        # print()
        sizes = resp.headers.get('image-size')
        if sizes is None:
            print(pathlib.Path(i), 'failed because it isnt found')
            continue
        matched = re.search('w=(\\d+), h=(\\d+)', sizes)
        uniname = pathlib.Path(i).parent.stem
        unidata[uniname] = unidata.get(uniname, {
            'humanName': univ.get(uniname, uniname),
            "noAi": dict(), "wiAi": dict()})
        unidata[uniname]['wiAi' if pathlib.Path(i).stem.endswith('-ai') else 'noAi'][pathlib.Path(i).suffix[1:]] = {
            'hash': f'{hash}{pathlib.Path(i).suffix}', 'w': int(matched.group(1)), 'h': int(matched.group(2)),
            'origin': 'universe', 't': resp.headers['image-type']}
    nokeys = set(unidata.keys())
    for thing in sorted(set(univ.keys()) - nokeys):
        unidata[thing] = {'humanName': univ[thing]}

    new = dict(main=local['main'])
    for key, val in local.items():
        if key == 'main':
            continue
        new[key] = val
    local = new
    step0 = [(key, val) for key, val in local['main'].items()]
    step0.sort(key=lambda thing: datetime.fromisoformat(thing[1]["main.json"]['creationDate']).timestamp())

    def get_sort_key(item):
        u_id = str(item[1]["main.json"].get('UniverseId', ''))
        is_favicond = 0 if u_id == 'Favicond-Main' else 1
        return is_favicond, unidata.get(u_id, dict()).get('humanName', u_id)

    # Sort the items according to UniverseId custom hierarchy
    sorted_items = sorted(step0, key=get_sort_key)

    # Reconstruct local['main'] back into its original dict structure { char_id: char_data }
    local['main'] = {char_id: char_data for char_id, char_data in sorted_items}
    pass  # gemini end
    copyfile('404placeholder.webp', '../imgdata/404placeholder.webp')
    with open(f'../{folder}/.assets.json', 'wt', encoding='utf8') as file:
        file.write(json.dumps(dict(
            chardata=local, unidata=unidata
        ), sort_keys=False, indent=2))
    pass


if __name__ == '__main__':
    main()
